packages:
  - packages/mm-rslib
  - packages/mm-vite-react
  - packages/mm-native-lynx-app
  - packages/mm-nuxt-better-auth-drizzle
  - packages/m-deno
onlyBuiltDependencies:
  - "@biomejs/biome"
  - core-js
  - esbuild
  - lefthook
