[template]
cargo_generate_version = ">=0.22.0"

[placeholders]
description = { type = "text", prompt = "Description of the monorepo member" }
scope = { type = "text", prompt = "Scope of the npm package" }

# ask_for_string = { type = "bool", prompt = "Make a choice too?", default = true }

# [conditional.'ask_for_string'.placeholders.choice]
# type = "string"
# prompt = "Please select one..."
# choices = ["One", "Two", "Three", "Four"]
