[template]
cargo_generate_version = ">=0.22.0"

[placeholders]
description = { type = "text", prompt = "Description of the monorepo member" }
scope = { type = "text", prompt = "Scope of the npm package" }
filesOnly = { type = "bool", prompt = "Is the package files only ?", default = false }

[conditional.filesOnly.placeholders.filesOnlyType]
type = "string"
prompt = "Please select one file type which src folder should contain (and error in index import - with test)"
choices = ["yml", "json"]
