name = "mm-rsbuild"
description = "Monorepo member with rslib"
kickstart_version = 1
authors = ["elcoosp"]
ignore = [".turbo", "node_modules"]
copy_without_render = []
directory = "template"
post_gen_hooks = [{ name = "Finish setup", path = "scripts/finish_setup.sh" }]
[[variables]]
name = "project_name"
default = "my-proj"
prompt = "Name (kebab-case) of the project"
validation = "^([a-z][a-zA-Z0-9_-]+)$"

[[variables]]
name = "org"
default = "my-org"
prompt = "Name (kebab-case) of the organization"
validation = "^([a-z][a-zA-Z0-9_-]+)$"

[[variables]]
name = "description"
default = "{{project_name}} rslib"
prompt = "Description of the project"

[[variables]]
name = "files_only"
default = true
prompt = "Is the package files only ?"

[[variables]]
name = "files_only_type"
default = "json"
prompt = "Please select one file type which src folder should contain (and error in index import - with test)"
only_if = { name = "files_only", value = true }
choices = ["yml", "json"]
