name = "m-rsbuild-plugin"
description = "Monorepo for an rsbuild plugin"
kickstart_version = 1
authors = ["elcoosp"]
ignore = [".turbo", "node_modules"]
copy_without_render = []
directory = "template"

[[variables]]
name = "project_name"
default = "my-proj"
prompt = "Name (kebab-case) of the project"
validation = "^([a-z][a-zA-Z0-9_-]+)$"
[[variables]]
name = "org"
default = "my-org"
prompt = "Name (kebab-case) of the organization"
validation = "^([a-z][a-zA-Z0-9_-]+)$"

[[variables]]
name = "description"
default = "{{project_name}} rsbuild plugin"
prompt = "Description of the project"
