[template]
cargo_generate_version = ">=0.22.0"
ignore = ["pnpm-lock.yaml", ".turbo", "node_modules", "deno.lock"]

[hooks]
pre = ["pre-script.rhai"]
post = ["post-script.rhai"]

[placeholders]
description = { type = "text", prompt = "Description of the monorepo" }
scope = { type = "text", prompt = "Scope of the monorepo (used in @{scope}/{pkgName})" }
members = { type = "text", prompt = "Space separated list of monorepo member names" }
versioner = { type = "string", prompt = "Which versioner?", choices = [
    "changesets",
], default = "changesets" }

# Readma
readma-repobeats = { type = "text", prompt = "Readma repobeats hash (not url)" }
