name = "mm-native-lynx-app"
description = "Monorepo member for a native lynx app"
kickstart_version = 1
authors = ["elcoosp"]
ignore = [
    "pnpm-lock.yaml",
    ".turbo",
    "node_modules",
    "template/android/Kotlin{{project_name}}/.gradle",
]
copy_without_render = [
    "template/src/routes/App.tsx",
    "template/src/routes/Home.tsx",
]
directory = "template"
post_gen_hooks = [{ name = "Finish setup", path = "scripts/finish_setup.sh" }]

[[variables]]
name = "project_name"
default = "MyProj"
prompt = "Name (PascalCase) of the project"
validation = "^([A-Z][a-zA-Z0-9_-]+)$"
[[variables]]
name = "org"
default = "myOrg"
prompt = "Name (camelCase) of the organization (com.{{org}}.{{project_name|camel_case}}"
validation = "^([a-z][a-zA-Z0-9_-]+)$"

[[variables]]
name = "description"
default = "{{project_name}} lynx app"
prompt = "Description of the project"
