name: CI

on:
  push:
    branches: '**'
  pull_request:
    types: [opened, synchronize]

jobs:
  call-workflow-passing-data:
    uses: elcoosp/elcoosp-configs/.github/workflows/ci.yml@main
    secrets: inherit